database_url: "cache.db"
use_curl: false
use_proxy: true
cache_hit_pool_size: 4
cache_miss_pool_size: 8
max_concurrent_requests: 100
cache_version: 0
cache_override_mode: false
# 缓存配置
cache:
  enabled: true               # 是否启用缓存功能
  max_items: 100              # 内存缓存最大条目数量
  batch_write_size: 20        # 批量写入数据库的数量
# 空闲刷新配置
idle_flush:
  enabled: true               # 是否启用空闲刷新功能
  idle_timeout_seconds: 300   # 空闲超时时间（秒）
  check_interval_seconds: 10  # 检查间隔时间（秒）
# 缓存清理配置
cache_maintenance:
  enabled: true                # 是否启用缓存维护
  interval_hours: 12           # 清理间隔时间（小时）
  retention_days: 30           # 保留天数
  cleanup_on_startup: false    # 启动时是否执行清理
  min_hit_count: 5             # 最小命中次数（低于此值的无引用答案会被清理）

# 上下文裁切配置
context_trim:
  enabled: false               # 是否启用上下文裁切功能
  max_context_tokens: 4096     # 允许的最大上下文token数量，超过后会裁切

api_endpoints:
  - url: "http://127.0.0.1:1234"
    weight: 1
    version: 0
    model: "gemma-3-text-4b-it"
  - url: "http://127.0.0.1:11434"
    weight: 2
    version: 1
    model: "llama3"
