database_url: "sqlite:cache.db"
cache_version: 0
cache_override_mode: true
use_curl: false
use_proxy: true
api_headers:
  Content-Type: "application/json"
  Accept: "application/json"
  User-Agent: "llm_api_rust_client/1.0"
api_endpoints:
  - url: "http://192.168.1.11:1234"
    weight: 0
    model: "maziyarpanahi/gemma-3-4b-it"
  - url: "http://127.0.0.1:11434"
    weight: 9
    model: "gemma3:4b"
  - url: "http://127.0.0.1:1234"
    weight: 1
    model: "gemma-3-text-4b-it-mlx"